language: node_js
node_js:
  - 16

branches:
  only:
    - develop

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # Build and tag feed-api
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed hungnv102/udagram-api-feed:v2
  # Build and tag feed-api
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user hungnv102/udagram-api-user:v1
  # Build and tag feed-api
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend hungnv102/udagram-frontend:v2
  # Build and tag feed-api
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy hungnv102/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hungnv102/udagram-api-feed:v3
  - docker push hungnv102/udagram-api-user:v3
  - docker push hungnv102/udagram-frontend:v3
  - docker push hungnv102/udagram-reverseproxy:v3